import path from 'path';
import { promises as fs } from 'fs';

/**
 * Where uploaded blast images live on disk.
 *
 * MUST point somewhere OUTSIDE the deployed release directory in production.
 * The server deploys into /var/www/fastmatch.com.au/releases/<timestamp> with
 * `current` symlinked at the newest one, so anything written inside the app
 * folder disappears on the next deploy — and every previously sent blast
 * would then have a broken image, permanently, in inboxes already delivered.
 *
 * Production (in shared/.env, alongside the other secrets):
 *   UPLOAD_DIR="/var/www/fastmatch.com.au/shared/uploads"
 *
 * Falls back to <project>/uploads for local development, which is gitignored.
 * Read lazily inside the functions — a module-scope env read that throws
 * would break `next build`, which imports every module.
 */
export function uploadDir(): string {
  return process.env.UPLOAD_DIR || path.join(process.cwd(), 'uploads');
}

/**
 * Filenames are generated by us (see the upload route), never taken from the
 * client's own filename — a name like "../../.env" would otherwise let an
 * upload escape the directory, and a read escape it in the other direction.
 * Both the write and the read side validate against this exact shape.
 */
const SAFE_NAME = /^[a-f0-9]{32}\.(jpg|png|webp)$/;

export function isSafeUploadName(name: string): boolean {
  return SAFE_NAME.test(name);
}

/** Absolute path for a stored upload, or null if the name isn't one of ours. */
export async function resolveUploadPath(name: string): Promise<string | null> {
  if (!isSafeUploadName(name)) return null;
  const full = path.join(uploadDir(), name);
  // Defence in depth: even with the regex above, confirm the resolved path
  // really sits inside the upload directory before touching the filesystem.
  const base = path.resolve(uploadDir());
  if (!path.resolve(full).startsWith(base + path.sep)) return null;
  try {
    await fs.access(full);
    return full;
  } catch {
    return null;
  }
}

export async function ensureUploadDir(): Promise<void> {
  await fs.mkdir(uploadDir(), { recursive: true });
}

/** The public URL an email or the admin preview should point at. */
export function uploadUrl(name: string): string {
  return `${(process.env.APP_URL ?? '').replace(/\/+$/, '')}/api/uploads/${name}`;
}
